// <auto-generated />
using System;
using CampusConnect.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnect.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Comentario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsInterno")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreAlmacenado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreArchivoOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RutaRelativa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SolicitudId")
                        .HasColumnType("int");

                    b.Property<int>("SubidoPorId")
                        .HasColumnType("int");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SolicitudId");

                    b.HasIndex("SubidoPorId");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Recurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Recursos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "LAB-SIS-05",
                            Descripcion = "PC de desarrollo para asignaturas de desarrollo y bases de datos",
                            Estado = 1,
                            FechaRegistro = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Equipo de Cómputo Dell Core i7",
                            Tipo = 2,
                            Ubicacion = "Edificio A - Laboratorio de Sistemas 1"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "AUD-PROY-01",
                            Descripcion = "Sistema de proyección para conferencias y ponencias",
                            Estado = 1,
                            FechaRegistro = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Proyector Láser Epson 4K",
                            Tipo = 2,
                            Ubicacion = "Edificio Central - Auditorio Mayor"
                        },
                        new
                        {
                            Id = 3,
                            Codigo = "AULA-204-CLIMA",
                            Descripcion = "Climatización de 24,000 BTU",
                            Estado = 1,
                            FechaRegistro = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Unidad Central de Aire Acondicionado",
                            Tipo = 1,
                            Ubicacion = "Edificio B - Aula Magna 204"
                        });
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Solicitud", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsignadoAId")
                        .HasColumnType("int");

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("CodigoTicket")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<int?>("RecursoId")
                        .HasColumnType("int");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAId");

                    b.HasIndex("CodigoTicket")
                        .IsUnique();

                    b.HasIndex("RecursoId");

                    b.HasIndex("SolicitanteId");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CarreraODepartamento")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CarreraODepartamento = "Ingeniería de Sistemas",
                            Correo = "juan.perez@universidad.edu",
                            FechaRegistro = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Juan Pérez (Estudiante)",
                            PasswordHash = "hashed_secret_password_123",
                            Rol = 1,
                            Telefono = "555-0101"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CarreraODepartamento = "Dirección de Infraestructura y Servicios",
                            Correo = "maria.gomez@universidad.edu",
                            FechaRegistro = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Dra. María Gómez (Administradora)",
                            PasswordHash = "hashed_secret_admin_123",
                            Rol = 2,
                            Telefono = "555-0202"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CarreraODepartamento = "Centro de Tecnologías de Información",
                            Correo = "carlos.rivas@universidad.edu",
                            FechaRegistro = new DateTime(2026, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Ing. Carlos Rivas (Soporte TI)",
                            PasswordHash = "hashed_secret_tech_123",
                            Rol = 3,
                            Telefono = "555-0303"
                        });
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Comentario", b =>
                {
                    b.HasOne("CampusConnect.Web.Models.Entities.Solicitud", "Solicitud")
                        .WithMany("Comentarios")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Web.Models.Entities.Usuario", "Usuario")
                        .WithMany("Comentarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Evidencia", b =>
                {
                    b.HasOne("CampusConnect.Web.Models.Entities.Solicitud", "Solicitud")
                        .WithMany("Evidencias")
                        .HasForeignKey("SolicitudId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnect.Web.Models.Entities.Usuario", "SubidoPor")
                        .WithMany("Evidencias")
                        .HasForeignKey("SubidoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Solicitud");

                    b.Navigation("SubidoPor");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Solicitud", b =>
                {
                    b.HasOne("CampusConnect.Web.Models.Entities.Usuario", "AsignadoA")
                        .WithMany("SolicitudesAsignadas")
                        .HasForeignKey("AsignadoAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CampusConnect.Web.Models.Entities.Recurso", "Recurso")
                        .WithMany("Solicitudes")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CampusConnect.Web.Models.Entities.Usuario", "Solicitante")
                        .WithMany("SolicitudesCreadas")
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AsignadoA");

                    b.Navigation("Recurso");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Recurso", b =>
                {
                    b.Navigation("Solicitudes");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Solicitud", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("CampusConnect.Web.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Evidencias");

                    b.Navigation("SolicitudesAsignadas");

                    b.Navigation("SolicitudesCreadas");
                });
#pragma warning restore 612, 618
        }
    }
}
